{
 "title": "Day1 Logs (Basic)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values({project=\"day1-lab\"}, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Log lines (last 15m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({project=\"day1-lab\"} [15m]))"
    }
   ]
  },
  {
   "title": "Logs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (service) (count_over_time({project=\"day1-lab\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Top services (last 15m)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "topk(10, sum by (service) (count_over_time({project=\"day1-lab\"} [15m])))"
    }
   ]
  }
 ]
}